#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "synapse-admin"
name = "Ketesa"
description.en = "Admin UI for Matrix homeservers, formerly Synapse Admin"
description.fr = "Interface d'administration pour serveurs Matrix, anciennement Synapse Admin"

version = "1.0.0~ynh1"

maintainers = ["Josué Tille"]

[upstream]
license = "Apache-2.0"
code = "https://github.com/etkecc/ketesa"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = "all"
multi_instance = false

ldap = false
sso = true

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/synapse-admin"

    [install.allowed_matrix_servers]
    ask.en = "Choose a Matrix server to allow the access or leave it empty to allow any synapse servers."
    type = "tags"
    optional = true
    example = "my-own-homeserver.tld"
    default = ""

    [install.init_main_permission]
    help.en = "If enabled, Ketesa will be accessible by people who do not have an account. This can be changed later via the webadmin."
    help.fr = "Si cette case est cochée, Ketesa sera accessible aux personnes n’ayant pas de compte. Vous pourrez changer ceci plus tard via la webadmin."
    type = "group"
    default = "visitors"

[resources]
    [resources.sources.main]
    url = "https://github.com/etkecc/ketesa/releases/download/v1.0.0/ketesa.tar.gz"
    sha256 = "1a27722c59cab2e4fca9fdedd994a92a9fc3bd6f83ae683003613db483faa814"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset = "ketesa.tar.gz"
    autoupdate.version_regex = "v(.*)"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"
